#!/usr/bin/env python3
# pidgin v0.2 — merged from tools/store/sections_chroma.py + tools/store/vectors.py (v0.1).
# Provenance: tools/store/sections_chroma.py (M6 sections store) +
#             tools/store/vectors.py (M8 function vectors).
# Behaviour: unchanged from v0.1 modules. Only modification is the import path
#   (tools.utils.api → pidgin.utils.api) and resolution of the _client()/_git_ref()
#   name collision — each origin module's private functions are now prefixed to
#   avoid shadowing (sections uses _sec_client/_sec_git_ref; vectors uses
#   _vec_client/_vec_git_ref). Public API is fully preserved.

# MODULE: nest
# DOES: ChromaDB persistent backend — section put/get/query (sections store) plus
#       function body and description upsert, search, and deletion (vector store).
#       Three collections: descriptions, function_bodies, function_descriptions.
# EMITS: ChromaDB document writes; (content, metadata) tuples on read;
#        hit lists on query/search; function ids on upsert
# READS: local/store/nest/ (ChromaDB persistent client); git HEAD ref at write time
# IMPLEMENTS: sections_chroma + vectors merged per M10 Provenance: NEW.
# DEPENDS: chromadb, hashlib, datetime, subprocess, os, pathlib, asyncio;
#          pidgin.utils.api (for embed_for_store)

import asyncio
import hashlib
import os
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import chromadb

from pidgin.utils import api
from pidgin.utils.git import find_project_root

# ---------------------------------------------------------------------------
# Module-level constants
# ---------------------------------------------------------------------------

# sections_chroma collection name
_COLLECTION_DESCRIPTIONS = "descriptions"

# vectors collection names
_COLLECTION_BODIES = "function_bodies"
_COLLECTION_FUNC_DESCRIPTIONS = "function_descriptions"

# Cached persistent client for the vector store path — shared with sections store
# (same ChromaDB instance, different collections).
_vec_client_cache: chromadb.api.ClientAPI | None = None


# ---------------------------------------------------------------------------
# Path helpers (both modules resolved to the same root)
# ---------------------------------------------------------------------------

def store_path() -> Path:
    """Return the canonical ChromaDB persistent store directory.

    Provenance: sections_chroma.store_path (v0.1). Canonical name retained
    for backward compat; vectors.py called this nest_path().
    """
    repo_root = Path(__file__).resolve().parent.parent.parent.parent
    return repo_root / "local" / "store" / "nest"


# _global_nest_path() — original alias retained internally.
def _global_nest_path() -> Path:
    """Return the canonical local/store/nest/ persistence directory (alias of store_path)."""
    return store_path()


# ---------------------------------------------------------------------------
# Per-repo nest helpers (M12)
# ---------------------------------------------------------------------------

def _resolve_nest_dir(anchor: str | None) -> str:
    """Resolve the canonical .pidgin/nest/ location for an anchor path.

    Walks up to .git. If no .git is found, falls back to anchor with a
    warning printed to stderr.
    """
    anchor = anchor or os.getcwd()
    root = find_project_root(anchor)
    if root is None:
        print(
            f"[nest] WARNING: no .git found above {anchor}; "
            f"using {anchor} as nest anchor.",
            file=sys.stderr,
        )
        root = anchor
    return os.path.join(root, ".pidgin", "nest")


def nest_path(repo_root: str) -> str:
    """Return the per-repo ChromaDB store path rooted at the git root.

    Walks up from repo_root to find the .git boundary. Falls back to
    repo_root itself if no .git ancestor exists (with a stderr warning).
    """
    return _resolve_nest_dir(repo_root)


def ensure_nest(repo_root: str) -> str:
    """Create <git_root>/.pidgin/nest/ if it does not exist. Return the path.

    git_root is resolved by walking up from repo_root to the nearest .git.
    Falls back to repo_root when no .git ancestor exists.
    """
    path = _resolve_nest_dir(repo_root)
    os.makedirs(path, exist_ok=True)
    return path


NEST_CLAUDE_MD_TEMPLATE = """\
# .pidgin/

This directory is the Pidgin nest for this repository.

- `nest/` — ChromaDB persistent store. Function descriptions, module
  summaries, behavioural contracts. Generated by `pidgin index`.
- `CLAUDE.md` — this file. Tells agents how to query the nest.

## Querying

```
pidgin query "what handles retry"
```

Returns the highest-similarity function descriptions from the nest.
The query is embedded with text-embedding-3-small @ 256 dim and
matched by cosine similarity.

## Re-Indexing

```
pidgin index . --write-db
```

Re-runs the MLD pipeline against current source. Existing nest entries
are upserted by file path + function name.

## Provenance

This file is auto-generated by `pidgin index`. Edit freely; the
generator will not overwrite an existing file.
"""


def write_nest_claude_md(repo_root: str, *, force: bool = False) -> str:
    """Write .pidgin/CLAUDE.md at the git root above repo_root.

    Resolves the git root by walking up from repo_root. Falls back to
    repo_root when no .git ancestor exists.
    Skips writing if the file already exists and force=False.
    Returns the path whether written or not.
    """
    resolved = find_project_root(repo_root) or repo_root
    path = os.path.join(resolved, ".pidgin", "CLAUDE.md")
    if os.path.exists(path) and not force:
        return path
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(NEST_CLAUDE_MD_TEMPLATE)
    return path


def _repo_nest_client(repo_root: str) -> chromadb.api.ClientAPI:
    """Open or create a persistent ChromaDB client at <repo_root>/.pidgin/nest/."""
    path = nest_path(repo_root)
    os.makedirs(path, exist_ok=True)
    settings = chromadb.Settings(
        anonymized_telemetry=False,
        allow_reset=True,
    )
    return chromadb.PersistentClient(path=path, settings=settings)


def _repo_descriptions_col(repo_root: str) -> chromadb.Collection:
    """Get-or-create the 'function_descriptions' collection in the per-repo nest."""
    client = _repo_nest_client(repo_root)
    return client.get_or_create_collection(
        name=_COLLECTION_FUNC_DESCRIPTIONS,
        embedding_function=None,
        metadata={"hnsw:space": "cosine"},
    )


def query(repo_root: str, text: str, n_results: int = 5) -> list[dict]:
    """Embed text and search the local nest at repo_root/.pidgin/nest/.

    Returns a list of hit dicts with keys: function_name, description, similarity, file.
    Returns [] if the nest does not exist or contains no results.
    """
    nest_dir = nest_path(repo_root)
    if not os.path.exists(nest_dir):
        return []

    try:
        col = _repo_descriptions_col(repo_root)
    except Exception:
        return []

    try:
        vectors = asyncio.run(api.embed_for_store(text))
    except RuntimeError:
        import concurrent.futures
        with concurrent.futures.ThreadPoolExecutor(max_workers=1) as ex:
            vectors = ex.submit(asyncio.run, api.embed_for_store(text)).result()

    query_vec = vectors[0]

    try:
        result = col.query(
            query_embeddings=[query_vec],
            n_results=n_results,
            include=["metadatas", "distances"],
        )
    except Exception:
        return []

    if not result or not result.get("ids") or not result["ids"][0]:
        return []

    ids = result["ids"][0]
    distances = (result.get("distances") or [[None] * len(ids)])[0]
    metadatas = (result.get("metadatas") or [[{}] * len(ids)])[0]

    hits = []
    for i in range(len(ids)):
        meta = metadatas[i] or {}
        dist = distances[i]
        similarity = (1.0 - dist) if dist is not None else 0.0
        hits.append({
            "function_name": meta.get("name", ids[i]),
            "description": meta.get("description", ""),
            "similarity": similarity,
            "file": meta.get("file", ""),
        })
    return hits


# ---------------------------------------------------------------------------
# Sections-store client and collection helpers
# ---------------------------------------------------------------------------

def _sec_client() -> chromadb.api.ClientAPI:
    """Open or create the persistent ChromaDB client at store_path() (sections side)."""
    path = store_path()
    path.mkdir(parents=True, exist_ok=True)
    settings = chromadb.Settings(
        anonymized_telemetry=False,
        allow_reset=True,
    )
    return chromadb.PersistentClient(path=str(path), settings=settings)


def _descriptions_col() -> chromadb.Collection:
    """Get-or-create the 'descriptions' collection for the sections store.

    embedding_function=None — we supply embeddings explicitly via api.embed_text.
    """
    client = _sec_client()
    return client.get_or_create_collection(
        name=_COLLECTION_DESCRIPTIONS,
        embedding_function=None,
        metadata={"hnsw:space": "cosine"},
    )


# ---------------------------------------------------------------------------
# Vector-store client and collection helpers
# ---------------------------------------------------------------------------

def _vec_client() -> chromadb.api.ClientAPI:
    """Open (or reuse) the persistent ChromaDB client at store_path() (vectors side).

    Cached at module level — Chroma's PersistentClient is intended to be a
    long-lived handle within a process.
    """
    global _vec_client_cache
    if _vec_client_cache is not None:
        return _vec_client_cache
    path = store_path()
    path.mkdir(parents=True, exist_ok=True)
    settings = chromadb.Settings(
        anonymized_telemetry=False,
        allow_reset=True,
    )
    _vec_client_cache = chromadb.PersistentClient(path=str(path), settings=settings)
    return _vec_client_cache


def _vec_collections() -> tuple[chromadb.Collection, chromadb.Collection]:
    """Return (function_bodies, function_descriptions) collections, creating if needed.

    Both collections configured with embedding_function=None — we always supply
    pre-computed vectors via embed_for_store and never let Chroma's default embedder run.
    """
    client = _vec_client()
    bodies = client.get_or_create_collection(
        name=_COLLECTION_BODIES,
        embedding_function=None,
        metadata={"hnsw:space": "cosine"},
    )
    descriptions = client.get_or_create_collection(
        name=_COLLECTION_FUNC_DESCRIPTIONS,
        embedding_function=None,
        metadata={"hnsw:space": "cosine"},
    )
    return (bodies, descriptions)


# ---------------------------------------------------------------------------
# Git and timestamp helpers (shared)
# ---------------------------------------------------------------------------

def _sec_git_ref() -> str | None:
    """Return short git HEAD ref, or None (sections-store version, may return None)."""
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip() or None
    except Exception:
        return None


def _vec_git_ref() -> str:
    """Return short git HEAD ref, or '' (vectors version, never returns None)."""
    try:
        out = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
        return out or ""
    except Exception:
        return ""


def _git_user() -> str:
    """Return git config user.name, or $USER, or 'unknown'."""
    try:
        name = subprocess.check_output(
            ["git", "config", "user.name"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
        return name or os.environ.get("USER", "unknown")
    except Exception:
        return os.environ.get("USER", "unknown")


def _now_utc_iso() -> str:
    """Return ISO-8601 UTC timestamp, second precision, e.g. 2026-04-25T12:34:56Z."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# ---------------------------------------------------------------------------
# Content hash and doc-id helpers (sections store)
# ---------------------------------------------------------------------------

def _hash(content: str) -> str:
    """Return first 8 hex chars of sha256(content)."""
    return hashlib.sha256(content.encode()).hexdigest()[:8]


def _doc_id(file: str, tag: str) -> str:
    """Compose the ChromaDB document ID as f'{file}:{tag}'."""
    return f"{file}:{tag}"


# ---------------------------------------------------------------------------
# ID generation (vector store)
# ---------------------------------------------------------------------------

def function_id(file: str, name: str, line_start: int) -> str:
    """Stable 16-char ID = sha256(f"{file}:{name}:{line_start}")[:16].

    Keyed on line_start so that growing a function body without moving its
    starting line produces the same ID — the upsert overwrites the prior row
    instead of leaking a duplicate.
    """
    key = f"{file}:{name}:{line_start}"
    return hashlib.sha256(key.encode()).hexdigest()[:16]


# ---------------------------------------------------------------------------
# Metadata builder (vector store)
# ---------------------------------------------------------------------------

def _build_function_metadata(
    *,
    file: str,
    name: str,
    line_start: int,
    line_end: int,
    description: str,
    language: str,
    module: str,
    visibility: str,
    natural_length: int,
    git_ref: str,
    signature_json: str | None = None,
    decorators_str: str | None = None,
) -> dict[str, Any]:
    """Assemble the metadata dict written into both function collections.

    Chroma metadata values must be str | int | float | bool.

    M12: Two optional fields added for full AST metadata:
      signature_json  — JSON-serialised FunctionSignature dict (str), or ""
                        when not provided (sentinel for pre-M12 records).
      decorators_str  — comma-joined decorator names (str), or "" when absent.
    Both default to "" so pre-M12 records are backward-compatible (Chroma
    is permissive — older rows simply lack these keys until re-indexed).
    """
    import json as _json
    meta: dict[str, Any] = {
        "file": file,
        "line_start": line_start,
        "line_end": line_end,
        "name": name,
        "language": language,
        "module": module,
        "visibility": visibility,
        "description": description,
        "natural_length": natural_length,
        "git_ref": git_ref,
        "signature_json": signature_json if signature_json is not None else "",
        "decorators_str": decorators_str if decorators_str is not None else "",
    }
    return meta


# ---------------------------------------------------------------------------
# Public API — sections store
# ---------------------------------------------------------------------------

def section_put_chroma(
    file: str,
    tag: str,
    content: str,
    *,
    model: str | None = None,
    doc_type: str = "function_description",
    confidence: float | None = None,
    converged: bool | None = None,
) -> bool:
    """Write a section to ChromaDB with hash idempotency.

    - Compute new_hash = _hash(content).
    - Read existing document by id = _doc_id(file, tag); if present and its
      metadata['source_hash'] == new_hash, return False (no write).
    - Otherwise embed content via api.embed_for_store and upsert with metadata:
      {file, tag, version, updated, by, model, source_hash, git_ref,
       doc_type, confidence, converged}
      where version = old_version + 1 if a prior row exists, else 1.
    - confidence: stored as float; -1.0 when None (-1.0 is an out-of-band
      sentinel since real confidences are clamped to [0.0, 1.0]).
    - converged: stored as bool; False when None.
    - Return True iff a write happened.
    """
    doc_id = _doc_id(file, tag)
    new_hash = _hash(content)

    collection = _descriptions_col()

    # Check for existing document.
    existing = collection.get(ids=[doc_id], include=["metadatas"])
    existing_meta = None
    if existing and existing["ids"]:
        existing_meta = existing["metadatas"][0]
        if existing_meta.get("source_hash") == new_hash:
            return False
        new_version = int(existing_meta.get("version", 0)) + 1
    else:
        new_version = 1

    # Embed content — handle running event loop (e.g. called from an async skill).
    try:
        loop = asyncio.get_running_loop()
    except RuntimeError:
        loop = None

    if loop is not None:
        import concurrent.futures
        with concurrent.futures.ThreadPoolExecutor(max_workers=1) as ex:
            vectors = ex.submit(asyncio.run, api.embed_for_store(content)).result()
    else:
        vectors = asyncio.run(api.embed_for_store(content))
    embedding = vectors[0]

    # Build metadata (ChromaDB metadata values must be str, int, float, or bool).
    git_ref = _sec_git_ref()
    meta: dict[str, Any] = {
        "file": file,
        "tag": tag,
        "version": new_version,
        "updated": _now_utc_iso(),
        "by": _git_user(),
        "source_hash": new_hash,
        "doc_type": doc_type,
        "model": model if model is not None else "",
        "git_ref": git_ref if git_ref is not None else "",
        "confidence": float(confidence) if confidence is not None else -1.0,
        "converged": bool(converged) if converged is not None else False,
    }

    collection.upsert(
        ids=[doc_id],
        documents=[content],
        embeddings=[embedding],
        metadatas=[meta],
    )
    return True


def section_get_chroma(file: str, tag: str) -> tuple[str, dict[str, Any]] | None:
    """Read a section from ChromaDB. Return (content, metadata_dict) or None."""
    doc_id = _doc_id(file, tag)
    collection = _descriptions_col()

    result = collection.get(ids=[doc_id], include=["documents", "metadatas"])
    if not result or not result["ids"]:
        return None

    content = result["documents"][0]
    metadata = result["metadatas"][0]
    return (content, metadata)


def section_query_chroma(
    *,
    where: dict[str, Any] | None = None,
    limit: int = 50,
) -> list[tuple[str, str, dict[str, Any]]]:
    """Filter ChromaDB by metadata. Return [(doc_id, content, metadata), ...].

    'where' is passed through to ChromaDB's get(where=...) — operators like
    {'doc_type': 'function_description', 'file': '/path/to/file.py'}.
    Returns up to `limit` rows.
    """
    collection = _descriptions_col()

    kwargs: dict[str, Any] = {
        "include": ["documents", "metadatas"],
        "limit": limit,
    }
    if where is not None:
        kwargs["where"] = where

    result = collection.get(**kwargs)
    if not result or not result["ids"]:
        return []

    return [
        (doc_id, doc, meta)
        for doc_id, doc, meta in zip(
            result["ids"], result["documents"], result["metadatas"]
        )
    ]


# ---------------------------------------------------------------------------
# Public API — vector store: upsert
# ---------------------------------------------------------------------------

async def upsert_function(
    file: str,
    name: str,
    line_start: int,
    line_end: int,
    body: str,
    *,
    description: str | None = None,
    language: str,
    module: str,
    visibility: str,
    natural_length: int,
    git_ref: str | None = None,
    signature_json: str | None = None,
    decorators_str: str | None = None,
) -> str:
    """Embed body (and optionally description) and upsert into ChromaDB.

    When ``description`` is provided (not None):
      - One batched embed_for_store([body, description]) call produces both
        vectors in a single round-trip.
      - Body vector → function_bodies. Description vector → function_descriptions.
      - Identical id and metadata in both collections for cross-lookup.

    When ``description`` is None (no MLD exists yet):
      - Only the body string is embedded via embed_for_store(body).
      - Upserted into function_bodies only.
      - function_descriptions is NOT written — querying it returns zero results
        until /digest runs (fail-safe, not stale).
      - Metadata on the body side records description="" and natural_length=0 as
        sentinels (Chroma rejects None values).

    Returns the function_id either way.
    """
    fid = function_id(file, name, line_start)
    resolved_git_ref = _vec_git_ref() if git_ref is None else git_ref
    bodies, descs_col = _vec_collections()

    if description is None:
        # Body-only path.
        vectors = await api.embed_for_store(body)
        body_vec = vectors[0]

        metadata = _build_function_metadata(
            file=file,
            name=name,
            line_start=line_start,
            line_end=line_end,
            description="",
            language=language,
            module=module,
            visibility=visibility,
            natural_length=0,
            git_ref=resolved_git_ref,
            signature_json=signature_json,
            decorators_str=decorators_str,
        )

        bodies.upsert(
            ids=[fid],
            documents=[body],
            embeddings=[body_vec],
            metadatas=[metadata],
        )
        # function_descriptions intentionally skipped — see docstring.
    else:
        # Dual-write path: two strings in, two vectors out.
        vectors = await api.embed_for_store([body, description])
        body_vec, desc_vec = vectors[0], vectors[1]

        metadata = _build_function_metadata(
            file=file,
            name=name,
            line_start=line_start,
            line_end=line_end,
            description=description,
            language=language,
            module=module,
            visibility=visibility,
            natural_length=natural_length,
            git_ref=resolved_git_ref,
            signature_json=signature_json,
            decorators_str=decorators_str,
        )

        bodies.upsert(
            ids=[fid],
            documents=[body],
            embeddings=[body_vec],
            metadatas=[metadata],
        )
        descs_col.upsert(
            ids=[fid],
            documents=[description],
            embeddings=[desc_vec],
            metadatas=[metadata],
        )

    return fid


# ---------------------------------------------------------------------------
# Public API — vector store: search
# ---------------------------------------------------------------------------

def _format_hits(result: dict) -> list[dict]:
    """Convert a Chroma query() result into the public hit shape.

    Public hit shape: {id, distance, file, line_start, line_end, name, description}.
    Chroma's query() returns each field as a list-of-lists (one inner list per
    query string). We always issue single-query searches, so we collapse [0].
    """
    if not result or not result.get("ids") or not result["ids"][0]:
        return []

    ids = result["ids"][0]
    distances = (result.get("distances") or [[None] * len(ids)])[0]
    metadatas = (result.get("metadatas") or [[{}] * len(ids)])[0]

    hits: list[dict] = []
    for i, fid in enumerate(ids):
        meta = metadatas[i] or {}
        hits.append({
            "id": fid,
            "distance": distances[i],
            "file": meta.get("file"),
            "line_start": meta.get("line_start"),
            "line_end": meta.get("line_end"),
            "name": meta.get("name"),
            "description": meta.get("description"),
        })
    return hits


async def find_by_body(query: str, k: int = 5) -> list[dict]:
    """Search function_bodies. "Find functions that handle X."

    Embeds the query string via embed_for_store, runs a vector search against
    function_bodies, and returns the top k hits as
    {id, distance, file, line_start, line_end, name, description}.
    """
    vectors = await api.embed_for_store(query)
    query_vec = vectors[0]

    bodies, _ = _vec_collections()
    result = bodies.query(
        query_embeddings=[query_vec],
        n_results=k,
        include=["metadatas", "distances"],
    )
    return _format_hits(result)


async def find_similar_to_description(description: str, k: int = 5) -> list[dict]:
    """Search function_descriptions. "Find functions similar to this one."

    Embeds the description via embed_for_store, runs a vector search against
    function_descriptions, and returns the top k hits in the same shape
    as find_by_body.
    """
    vectors = await api.embed_for_store(description)
    query_vec = vectors[0]

    _, descriptions = _vec_collections()
    result = descriptions.query(
        query_embeddings=[query_vec],
        n_results=k,
        include=["metadatas", "distances"],
    )
    return _format_hits(result)


# ---------------------------------------------------------------------------
# Public API — vector store: maintenance
# ---------------------------------------------------------------------------

def delete_function(fid: str) -> None:
    """Remove the entry from both function collections.

    Used when a function is deleted from source. Idempotent — deleting a
    non-existent id is a Chroma no-op.
    """
    bodies, descriptions = _vec_collections()
    bodies.delete(ids=[fid])
    descriptions.delete(ids=[fid])


def reset_all() -> None:
    """Drop both function collections and recreate them. Test/dev use only.

    Does NOT touch the sections store's 'descriptions' collection — safe to
    call without affecting sections data.
    """
    global _vec_client_cache
    client = _vec_client()
    for name in (_COLLECTION_BODIES, _COLLECTION_FUNC_DESCRIPTIONS):
        try:
            client.delete_collection(name=name)
        except Exception:
            pass
    # Recreate empties so the next caller hits warm collections.
    _vec_collections()


# ---------------------------------------------------------------------------
# Public API — CLI index verb helper
# ---------------------------------------------------------------------------

def query_by_path(nest_path: str, text: str, n_results: int = 5) -> list[dict]:
    """Embed text and search the nest at the given direct nest_path (not repo_root).

    Unlike query(), this function takes the absolute path to the .pidgin/nest/
    directory itself, enabling callers to search nests discovered via the registry
    without having to reconstruct a repo_root.

    Returns a list of hit dicts with keys: function_name, description, similarity, file.
    Returns [] if the nest does not exist, is empty, or fails to open (e.g. corrupt
    sqlite3 file). ChromaDB open errors are caught and logged as warnings rather than
    raised, so a multi-nest search can continue past failed nests.
    """
    if not os.path.isdir(nest_path):
        return []

    try:
        settings = chromadb.Settings(
            anonymized_telemetry=False,
            allow_reset=True,
        )
        client = chromadb.PersistentClient(path=nest_path, settings=settings)
        col = client.get_or_create_collection(
            name=_COLLECTION_FUNC_DESCRIPTIONS,
            embedding_function=None,
            metadata={"hnsw:space": "cosine"},
        )
    except Exception as exc:
        import warnings
        warnings.warn(f"[query_by_path] Could not open ChromaDB at {nest_path}: {exc}")
        return []

    try:
        vectors = asyncio.run(api.embed_for_store(text))
    except RuntimeError:
        import concurrent.futures
        with concurrent.futures.ThreadPoolExecutor(max_workers=1) as ex:
            vectors = ex.submit(asyncio.run, api.embed_for_store(text)).result()

    query_vec = vectors[0]

    try:
        result = col.query(
            query_embeddings=[query_vec],
            n_results=n_results,
            include=["metadatas", "distances"],
        )
    except Exception:
        return []

    if not result or not result.get("ids") or not result["ids"][0]:
        return []

    ids = result["ids"][0]
    distances = (result.get("distances") or [[None] * len(ids)])[0]
    metadatas = (result.get("metadatas") or [[{}] * len(ids)])[0]

    hits = []
    for i in range(len(ids)):
        meta = metadatas[i] or {}
        dist = distances[i]
        similarity = (1.0 - dist) if dist is not None else 0.0
        hits.append({
            "function_name": meta.get("name", ids[i]),
            "description": meta.get("description", ""),
            "similarity": similarity,
            "file": meta.get("file", ""),
        })
    return hits


def upsert_function_descriptions(
    repo_root: str,
    results: list,
    functions: list[dict] | None = None,
    *,
    file_meta: dict | None = None,
) -> None:
    """Upsert FunctionMldResult list into the per-repo <repo_root>/.pidgin/nest/ ChromaDB.

    Provenance: v0.1 section_put in tools/store/sections_chroma.py.
    M12: Fixed to write to per-repo .pidgin/nest/ (not global local/store/nest/).
    M9-patch: Added optional `functions` parameter (parallel list of function dicts
    from extract_public_functions). When provided, the "file" metadata field is set
    to the per-function source file path (fn["file"]). When absent, falls back to
    str(repo_root) for backward compatibility.
    M12-patch: Added optional `file_meta` parameter ({rel_path: FileMeta} lookup built
    by index.py). When provided, the per-function FunctionSignature is serialised to
    JSON and stored as signature_json; decorator names are stored as decorators_str.

    For each FunctionMldResult with at least one candidate description, picks
    the candidate at index 0 from the dominant cluster (first candidate is
    representative of the converged cluster when converged=True, or the best
    available when not converged). Upserts into the per-repo function_descriptions
    collection keyed by function_id(repo_root, result.name, 0).

    When no candidates exist for a result, the result is skipped silently.
    """
    from dataclasses import asdict
    import json as _json
    from pathlib import Path as _Path

    col = _repo_descriptions_col(repo_root)
    git_ref = _vec_git_ref()

    for i, result in enumerate(results):
        if not result.candidates:
            continue
        description = result.candidates[0]
        fid = function_id(str(repo_root), result.name, 0)

        # Resolve per-function file path from the parallel functions list when provided.
        fn = functions[i] if (functions is not None and i < len(functions)) else {}
        if fn:
            file_path = fn.get("file", str(repo_root))
        else:
            file_path = str(repo_root)

        # M12-patch: look up FunctionSignature from the file_meta dict.
        sig_json = ""
        dec_str = ""
        if file_meta and fn:
            rel = fn.get("file", "")
            fm = file_meta.get(rel)
            if fm is None and rel:
                # try resolving relative to repo_root
                try:
                    rel_key = str(_Path(rel).relative_to(repo_root))
                    fm = file_meta.get(rel_key)
                except Exception:
                    pass
            if fm is not None:
                func_name = fn.get("name", result.name)
                sig = next(
                    (s for s in fm.functions if s.name == func_name),
                    None,
                )
                if sig is not None:
                    sig_json = _json.dumps(asdict(sig))
                    dec_str = ",".join(sig.decorators)

        # Embed the description for the per-repo store.
        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            loop = None

        if loop is not None:
            import concurrent.futures
            with concurrent.futures.ThreadPoolExecutor(max_workers=1) as ex:
                vectors = ex.submit(asyncio.run, api.embed_for_store(description)).result()
        else:
            vectors = asyncio.run(api.embed_for_store(description))
        desc_vec = vectors[0]

        # M13: pull source_hash from the parallel function dict if present.
        # Empty string means "no hash known" — diff_against_nest will treat
        # any pre-M13 record as UPDATED on the next index pass.
        src_hash = ""
        if fn:
            src_hash = fn.get("source_hash", "") or ""

        metadata = {
            "file": file_path,
            "name": result.name,
            "description": description,
            "converged": bool(result.converged),
            "git_ref": git_ref,
            "line_start": 0,
            "line_end": 0,
            "language": "python",
            "module": "",
            "visibility": "public",
            "natural_length": len(description),
            "signature_json": sig_json,
            "decorators_str": dec_str,
            "source_hash": src_hash,
        }

        col.upsert(
            ids=[fid],
            documents=[description],
            embeddings=[desc_vec],
            metadatas=[metadata],
        )


# ---------------------------------------------------------------------------
# Public API — egg verb helper (M9)
# ---------------------------------------------------------------------------

class FunctionRecord:
    """Lightweight record yielded by iter_records.

    Fields used by pidgin egg:
      file_path      — absolute path to the source file.
      symbol_name    — function or class name.
      symbol_kind    — "function" | "class" | etc. (from metadata.language field,
                       defaulting to "function" when absent).
      mld_description — the MLD description string (may be empty).
      file_summary   — one-paragraph file-level summary from the sections store,
                       or None when no summary has been generated yet.
      signature      — dict from FunctionSignature.asdict(), or None when the nest
                       was written before M12 (older records lack this field).
      decorators     — list of decorator strings, or [] when absent.
      source_hash    — sha256 hex of the normalised function source (M13).
                       Empty string for records written before M13 — those
                       count as UPDATED on first re-index, forcing one re-MLD.
      record_id      — the ChromaDB document ID this record came from (M13).
                       Used by prune() to delete by id without re-deriving it.
    """

    __slots__ = (
        "file_path", "symbol_name", "symbol_kind", "mld_description",
        "file_summary", "signature", "decorators", "source_hash", "record_id",
    )

    def __init__(
        self,
        file_path: str,
        symbol_name: str,
        symbol_kind: str,
        mld_description: str,
        file_summary: str | None,
        signature: "dict | None" = None,
        decorators: "list[str] | None" = None,
        source_hash: str = "",
        record_id: str = "",
    ) -> None:
        self.file_path = file_path
        self.symbol_name = symbol_name
        self.symbol_kind = symbol_kind
        self.mld_description = mld_description
        self.file_summary = file_summary
        self.signature = signature
        self.decorators: list[str] = decorators if decorators is not None else []
        self.source_hash = source_hash
        self.record_id = record_id


def iter_records(repo_root: str):
    """Yield FunctionRecord objects for every entry in <repo_root>/.pidgin/nest/.

    Reads function_descriptions collection from the per-repo ChromaDB.
    For each unique file_path found, fetches the file-level summary from
    the global sections store (section_get_chroma(file_path, "file_summary")).

    Yields nothing (empty iterator) when the nest does not exist or is empty.
    Callers (e.g. egg) check for emptiness and exit 1 accordingly.
    """
    nest_dir = nest_path(repo_root)
    if not os.path.isdir(nest_dir):
        return

    try:
        col = _repo_descriptions_col(repo_root)
        result = col.get(include=["metadatas", "documents"])
    except Exception:
        return

    if not result or not result.get("ids"):
        return

    ids = result["ids"]
    metadatas = result.get("metadatas") or [{}] * len(ids)
    documents = result.get("documents") or [""] * len(ids)

    # Pre-fetch file summaries for all unique files in one pass.
    file_summary_cache: dict[str, str | None] = {}
    for meta in metadatas:
        fp = (meta or {}).get("file", "")
        if fp and fp not in file_summary_cache:
            row = section_get_chroma(fp, "file_summary")
            file_summary_cache[fp] = row[0] if row else None

    for i, fid in enumerate(ids):
        import json as _json
        meta = metadatas[i] or {}
        fp = meta.get("file", "")
        name = meta.get("name", fid)
        # symbol_kind: nest metadata does not carry a kind field today; default
        # to "function".  When M12 adds class support this will be populated.
        kind = meta.get("symbol_kind", "function")
        desc = documents[i] or meta.get("description", "")
        summary = file_summary_cache.get(fp)
        # M12: deserialise signature_json back to dict; empty string → None.
        sig_raw = meta.get("signature_json", "") or ""
        try:
            signature = _json.loads(sig_raw) if sig_raw else None
        except Exception:
            signature = None
        # M12: deserialise comma-joined decorators_str back to list.
        dec_raw = meta.get("decorators_str", "") or ""
        decorators = [d for d in dec_raw.split(",") if d] if dec_raw else []
        # M13: surface source_hash and record id for the idempotency diff.
        source_hash = meta.get("source_hash", "") or ""
        yield FunctionRecord(
            file_path=fp,
            symbol_name=name,
            symbol_kind=kind,
            mld_description=desc,
            file_summary=summary,
            signature=signature,
            decorators=decorators,
            source_hash=source_hash,
            record_id=fid,
        )


# ---------------------------------------------------------------------------
# Public API — index idempotency (M13)
# ---------------------------------------------------------------------------
#
# The index verb builds a parallel list of (file, function_name, source_hash)
# from the source tree, then asks diff_against_nest to classify each entry
# against the existing nest:
#
#   UNCHANGED  — same identity key, same source_hash. No MLD; no embed; no upsert.
#   UPDATED    — same identity key, different source_hash (or empty source_hash
#                in the existing record, i.e. pre-M13). Re-MLD and re-upsert.
#   NEW        — identity key not in the nest. MLD and upsert.
#   DELETED    — record in nest but no matching identity key in the source tree.
#                Hard-deleted via prune().
#
# Identity key: (file_rel_path, function_name).
#
# Concurrency assumption: index runs single-process. No file-level locking on
# .pidgin/. A future parallel-index implementation must add locking before
# reading the existing nest contents.

@dataclass
class IdempotencyDiff:
    """Classification of source functions against the nest.

    Fields:
      unchanged — list[FunctionRecord]
        Records whose source_hash matches the source tree. Skipped entirely.
      updated   — list[tuple[FunctionRecord, dict]]
        Pairs of (existing record, new function dict from extract_public_functions).
        Re-MLD using the new dict; the old record is overwritten on upsert.
      new       — list[dict]
        Function dicts present in the source tree but not in the nest. MLD them.
      deleted   — list[FunctionRecord]
        Records present in the nest but absent from the source tree. Pruned.
    """
    unchanged: list = field(default_factory=list)
    updated:   list = field(default_factory=list)
    new:       list = field(default_factory=list)
    deleted:   list = field(default_factory=list)


def _identity_key(file_rel_path: str, name: str) -> tuple:
    """Return the canonical identity key used by the M13 idempotency diff.

    Tuple of (file_rel_path, name). file_rel_path is whatever string the
    caller threads through — typically a path relative to repo_root. The
    diff treats the key as opaque: equality comparison only.
    """
    return (file_rel_path, name)


def diff_against_nest(
    repo_root: str,
    new_functions: list,
) -> IdempotencyDiff:
    """Compare the source-tree function list against the existing nest.

    Args:
      repo_root: absolute path to the project root. Used to open the
        per-repo nest at <repo_root>/.pidgin/nest/. If the nest does not
        exist (first-ever index), every input function is classified NEW.
      new_functions: iterable of (file_rel_path, fn_dict) pairs. Each
        fn_dict must contain at least 'name' and 'source_hash' keys (the
        index verb populates source_hash via parser.function_dict_hash).

    Returns:
      IdempotencyDiff. Identity key is (file_rel_path, fn['name']).

    Pre-M13 records (those without a source_hash field, or with an empty
    string) are reported as UPDATED — their first re-index re-MLDs once
    and writes the hash, after which they remain UNCHANGED until the
    source actually changes.
    """
    # Build a lookup of existing records keyed by (file, name).
    nest_records_by_key: dict = {}
    for rec in iter_records(repo_root):
        key = _identity_key(rec.file_path, rec.symbol_name)
        nest_records_by_key[key] = rec

    diff = IdempotencyDiff()
    seen_keys: set = set()

    for file_rel_path, fn in new_functions:
        name = fn.get("name", "")
        key = _identity_key(file_rel_path, name)
        seen_keys.add(key)

        existing = nest_records_by_key.get(key)
        new_hash = fn.get("source_hash", "") or ""

        if existing is None:
            diff.new.append(fn)
            continue

        # Pre-M13 records have an empty source_hash. Treat as UPDATED so the
        # first index pass after the upgrade re-MLDs once and populates the
        # hash field. Subsequent passes will resolve to UNCHANGED.
        if not existing.source_hash or existing.source_hash != new_hash:
            diff.updated.append((existing, fn))
        else:
            diff.unchanged.append(existing)

    # Anything in the nest that we did not visit is DELETED.
    for key, rec in nest_records_by_key.items():
        if key not in seen_keys:
            diff.deleted.append(rec)

    return diff


def prune(repo_root: str, record_ids: list) -> int:
    """Hard-delete records from the per-repo nest by ChromaDB document id.

    Used by the index verb to remove DELETED records (functions that were
    in the nest but are no longer in the source tree). Hard-delete chosen
    over soft-tombstone because no caller depends on tombstoned function
    records — egg, query, and depends all skip records they cannot
    correlate to a live source file.

    Returns the number of ids requested for deletion (Chroma silently
    ignores ids that do not exist, so this is a best-effort count).
    Returns 0 immediately if record_ids is empty.
    """
    if not record_ids:
        return 0
    try:
        col = _repo_descriptions_col(repo_root)
        col.delete(ids=list(record_ids))
    except Exception as exc:
        print(
            f"[nest] WARNING: prune failed for {len(record_ids)} ids: {exc}",
            file=sys.stderr,
        )
        return 0
    return len(record_ids)
